apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: argosay-
spec:
  templates:
  - name: argosay
    container:
      image: argoproj/argosay:v1
      command: [sh, -c]
      args:
        - 'cowsay hello'
