apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: coinflip-
spec:
  templates:
  - name: coinflip
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import random
        result = "heads" if random.randint(0,1) == 0 else "tails"
        print(result)
