apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: print-message-template
spec:
  templates:
  - name: print-message
    inputs: 
      parameters: 
      - name: message
    container:
      image: alpine:latest
      command: [sh, -c]
      args:
        - 'echo'
        - '{{inputs.parameters.message}}'
