apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: print-message-template
spec:
  templates:
  - name: print-message
    container:
      image: alpine:latest
      command: [sh, -c]
      args:
        - 'echo result was: {{inputs.parameters.message}}'
