apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: forever
spec:
  templates:
  - name: forever
    container:
      image: docker/whalesay:latest
      command: [sh, "-c", "for I in $(seq 1 1000) ; do echo $I ; sleep 1s; done"]
