apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: gcr-step
spec:
  templates:
  - name: fetch-latest-image
    inputs: 
      parameters: 
      - name: image-repo
    script:
      image: google/cloud-sdk:alpine
      command: [bash]
      volumeMounts:
      - name: gcloud-service-account-secret
        mountPath: "/secret"
      source: |
        apk add jq
        gcloud auth activate-service-account --key-file secret/key.json
        IMAGE_TAG=$(gcloud container images list-tags {{inputs.parameters.image-tag}} --format json | jq -r '.[0] .tags[0]')
        echo $IMAGE_TAG > new_image_tag.txt
    outputs:
      parameters:
      - name: image-tag
        valueFrom:
          path: new_image_tag.txt
