apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: heads-
spec:
  templates:
  - name: heads
    container:
      image: alpine:3.6
      command: [sh, -c]
      args:
        - 'echo \"it was heads\"'
