apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: influxdb
spec:
  templates:
  - name: influxdb
    container:
      image: influxdb:1.2
      readinessProbe:
        httpGet:
          path: /ping
          port: 8086
        initialDelaySeconds: 5
        timeoutSeconds: 1
