apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: random-fail
spec:
  templates:
  - name: random-fail
    container:
      image: python:alpine3.6
      command: [python, -c]
