apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: argocd-sync-and-wait
  namespace: argo
spec:
  workflowMetadata:
  entrypoint: argocd-sync-and-wait
  templates:
    - name: argocd-sync-and-wait
      outputs:
        parameters:
          - name: greenops-argocd-info
            valueFrom:
              path: greenops-output.txt
          - name: out-param
            value: out-param-value
        artifacts:
          - name: hello-art
            path: /tmp/hello_world.txt
      inputs:
        parameters:
          - name: argocd-version
            value: v1.6.0
          - name: application-name
