apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: asdf
spec:
  entrypoint: entry
  templates:
  - name: entry
    dag:
      tasks:
      - name: asdf
        templateRef:
          name: test
          template: kaniko
        arguments:
          parameters:
          - name: repo
            value: "{{workflow.parameters.asdf-repo}}"
          - name: branch
            value: "{{workflow.parameters.asdf-branch}}"
          - name: docker-work-dir
            value: "{{workflow.parameters.asdf-docker-work-dir}}"
          - name: image-repo-path-tag
            value: "{{workflow.parameters.asdf-image-repo-path-tag}}"
          - name: step-name
            value: "{{workflow.parameters.asdf-step-name}}"
          - name: pipeline-name
            value: "{{workflow.parameters.asdf-pipeline-name}}"
          - name: team-name
            value: "{{workflow.parameters.asdf-team-name}}"